-- DDL
CREATE TABLE HRSYS (
	USR_UDF_RETIRE_STATUS CHAR(1),
	USR_LOGIN VARCHAR(200),
	USR_START_DATE DATE,
	USR_END_DATE DATE,
	USR_LAST_NAME VARCHAR(400),
	USR_FIRST_NAME VARCHAR(200),
	USR_UDF_KORNAME VARCHAR(600),
	USR_UDF_ENGNAME VARCHAR(600),
	USR_UDF_DEPT_CEN_CODE VARCHAR(200),
	USR_UDF_DEPT_CEN_NAME VARCHAR(600),
	USR_UDF_USER_CLASSI_NAME VARCHAR(600),
	USR_UDF_USER_CLASSI_CODE VARCHAR(200),
	USR_EMAIL VARCHAR(600),
	USR_UDF_POS_CODE VARCHAR(200),
	USR_UDF_AUTOPASS_POS_NAME VARCHAR(600),
	USR_UDF_AUTOPASS_POS_CODE VARCHAR(200),
	USR_UDF_AUTOPASS_LOCATION_CODE VARCHAR(200),
	USR_UDF_AUTOPASS_LOCATION_NAME VARCHAR(600),
	USR_DESCRIPTION VARCHAR(600),
	USR_UPDATE_DATE DATE
);


-- 더미데이터 제작 SQL
BEGIN
FOR i IN 1..50 LOOP
INSERT INTO HRSYS(
	USR_UDF_RETIRE_STATUS,
	USR_LOGIN,
	USR_START_DATE,
	USR_END_DATE,
	USR_LAST_NAME,
	USR_FIRST_NAME,
	USR_UDF_KORNAME,
	USR_UDF_ENGNAME,
	USR_UDF_DEPT_CEN_CODE,
	USR_UDF_DEPT_CEN_NAME,
	USR_UDF_USER_CLASSI_NAME,
	USR_UDF_USER_CLASSI_CODE,
	USR_EMAIL,
	USR_UDF_POS_CODE,
	USR_UDF_AUTOPASS_POS_NAME,
	USR_UDF_AUTOPASS_POS_CODE,
	USR_UDF_AUTOPASS_LOCATION_CODE,
	USR_UDF_AUTOPASS_LOCATION_NAME,
	USR_DESCRIPTION,
	USR_UPDATE_DATE
	) 
VALUES(
	'Y',
	CONCAT('sampleID', i),
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP,
	CONCAT('길동', i),
	CONCAT('홍', i),
	CONCAT('홍길동', i),
	CONCAT('HONGGILDONG', i),
	CONCAT('UG000000', i),
	CONCAT('부서', i),
	CONCAT('CLASSI', i),
	CONCAT('IG000000', i),
	CONCAT('qms@naver.com', i),
	CONCAT('POS0000', i),
	CONCAT('UDF0000', i),
	CONCAT('AUTOPASS', i),
	CONCAT('APL0000', i),
	CONCAT('AUTOPASSLOCATION', i),
	CONCAT('설명', i),
	CURRENT_TIMESTAMP
	);
END LOOP;
END;