INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(1, '허윤석', 'ysheo', '주임', 'IM팀', '2022-05-30', '1997-02-20');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(2, '안경진', 'akj', '주임', 'IM팀', '2022-09-01', '1995-11-01');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(3, '김광연', 'kgy', '주임', 'IM팀', '2022-07-13', '1993-05-10');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(4, '조현진', 'jhj', '주임', 'IM팀', '2022-07-13', '9999-12-31');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(5, '김정민', 'kjm', '주임', 'IM팀', '2022-08-01', '9999-12-31');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(6, '박재욱', 'pju', '대리', 'IM팀', '2022-11-01', '9999-12-31');

INSERT INTO stsboot.HUMAN_RESOURCE
(IM_KEY, IM_USER_NAME_KR, IM_USER_NAME_EN, IM_USER_RANK, IM_DEPT, IM_HIRE_DATE, BIRYMD)
VALUES(7, '추진협', 'cjh', '주임', '연구소', '2022-04-01', '9999-12-31');